version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.9.1
    container_name: rag_bi_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
